services:

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --hostname=keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  msproductos:
    build: ./msproductos
    container_name: msproductos
    ports:
      - "8082:8082"

  msalmacen:
    build: ./msalmacen
    container_name: msalmacen
    ports:
      - "8083:8083"

  msventa:
    build: ./msventa
    container_name: msventa
    ports:
      - "8084:8084"

  msgateway:
    build: ./msgateway
    container_name: msgateway
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
      - msproductos
      - msalmacen
      - msventa